package com.broker;

public enum EventType {
    // Register
    USER_REGISTER_REQUESTED,
    USER_REGISTER_SUCCESS,
    USER_REGISTER_FAILED,

    // Login
    USER_LOGIN_REQUEST,
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAILED,

    // Logout
    USER_LOGOUT_REQUEST,
    USER_LOGGED_OUT,

    // Account Management
    ACCOUNT_VIEW_REQUESTED,
    ACCOUNT_EDIT_REQUESTED,
    ACCOUNT_VIEW_RETURNED,
    ACCOUNT_UPDATE_SUCCESS,
    ACCOUNT_UPDATE_FAILED,

    // Item Management
    ITEM_BROWSE_REQUESTED,
    ITEM_SEARCH_REQUESTED,
    ITEM_LIST_RETURNED,
    ITEM_LIKE_REQUESTED,
    ITEM_REFILL_REQUESTED,
    ITEM_UPLOAD_REQUESTED,
    ITEM_REMOVE_REQUESTED,
    ITEM_EDIT_REQUESTED,
    ITEM_UPDATE_SUCCESS,

    // Wishlist Management
    WISHLIST_ADD_REQUESTED,
    WISHLIST_ADD_SUCCESS,
    WISHLIST_ADD_FAILED,
    WISHLIST_VIEW_REQUESTED,
    WISHLIST_DETAILS_RETURNED,
    WISHLIST_REMOVE_REQUESTED,
    WISHLIST_REMOVE_SUCCESS,
    WISHLIST_REMOVE_FAILED,
    WISHLIST_CLEAR_PURCHASED_REQUESTED,

    // Purchase/Payment/Order
    PURCHASE_REQUESTED,
    PURCHASE_FAILED_STOCK,
    PAYMENT_AUTHORIZATION_REQUESTED,
    PAYMENT_AUTHORIZED,
    PAYMENT_DENIED,
    ORDER_CREATED_REQUESTED,
    ORDER_CONFIRMED,
    ORDER_PAYMENT_FAILED,
    INVENTORY_ADJUST_REQUESTED,
    EMAIL_RECEIPT_REQUESTED,

    // Order Management
    ORDER_HISTORY_REQUESTED,
    ORDER_HISTORY_RETURNED,
    ORDER_TRACK_REQUESTED,
    ORDER_STATUS_RETURNED,
    ORDER_CANCEL_REQUESTED,
    ORDER_CANCEL_SUCCESS,
    ORDER_CANCEL_FAILED,
    REFUND_PROCESS_REQUESTED,
    REFUND_SUCCESS,
    REFUND_FAILED,

    // Shipping
    SHIPPING_STATUS_UPDATED,
    SHIPPING_REQUESTED,
    SHIPPING_PICKED_UP,
    SHIPPING_IN_TRANSIT,
    SHIPPING_OUT_FOR_DELIVERY,
    SHIPPING_DELIVERED,

    // Messaging
    MESSAGE_SEND_REQUESTED,
    MESSAGE_SENT_CONFIRMATION,
    STAFF_NOTIFIED_NEW_MESSAGE,
    MESSAGE_LIST_REQUESTED,
    MESSAGE_LIST_RETURNED,
    MESSAGE_REPLY_REQUESTED,
    MESSAGE_REPLY_SUCCESS,
    MESSAGE_HISTORY_REQUESTED,
    MESSAGE_HISTORY_RETURNED,
    CONVERSATION_LIST_REQUESTED,
    CONVERSATION_LIST_RETURNED,
    CONVERSATION_LOAD_REQUESTED,
    CONVERSATION_MESSAGES_RETURNED,
    UNREAD_MESSAGES_REQUESTED,
    UNREAD_MESSAGES_RETURNED,
    MESSAGE_MARKED_AS_READ,
    CUSTOMER_NOTIFIED_NEW_REPLY,
    CUSTOMER_INFO_ACCESS_REQUESTED,
    CUSTOMER_INTO_RETURNED,

    // Reporting
    TIMER_TRIGGER_DAILY_REPORT,
    TIMER_TRIGGER_MONTHLY_REPORT,
    REPORT_GENERATION_COMPLETE,
    REPORT_VIEW_REQUESTED,
    REPORT_DETAILS_RETURNED,

    // Notification
    NOTIFICATION_SENT,
    NOTIFICATION_FAILED
}
